apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: patient-service
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/guru423/medconnect-patient-service
    targetRevision: HEAD
    path: k8s
  destination:
    server: https://kubernetes.default.svc
    namespace: medconnect-dev
  syncPolicy:
    automated:
      prune: true
      selfHeal: true