---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: patient-db-secret
  namespace: medconnect-dev
spec:
  encryptedData:
    DB_PASSWORD: AgBVVtqdTx9TNG3GE/FXEx8rNMpoZqVdsVTh5MxlaTdPDXHqg0t3/78vORrdzV2mfM2FJKQn57ChpIS8nZeRyYEhrT/I4l+gowwUBVBtTSn5UewvmEHfVKI5p0/CRfyNqHUIe9jVxuOSXuVqnv/3aRyymWy0t1VWPoTGQX3K6FeoOobo4U/89NDO0xapA55bywisQaAOov6T44xeCSGkA7sn/ts+u7Vvh19FxrMi+XkEcdzm5vDfT9FsJ+sg82rSDo08o3tf/YRakBNWrfLftJGcq81tQyc4+8tMOwUcSIfKW9Jkr2cKWQs0JgfSV7p2YWt4FeG56lIxDU+wd0H/P15Ncbnth/JjhOeA9//CxoQsdMzq2TQabNCinuQowxUJVm9JMHnPZ55mCBkXGc0VWQ06FtZZ/GdSPNDHrSdSPddZZuIJ/NIrPosQnnMvZK9G276/6Fr1yFyXP+niJ+B5dIG/3oJJlK74EJf21fweypk0E+20X+QD3XoVDI46tX3P0AhGvNW1YSZjjVK145z9OUL7m8pnZc++m5q5GzSgmbFUW/tI5oPV8ms3P6Oqua4dvp7GNh+PSSK9TYijvnybWZ+AUdsgARvtLA/VzbI233nXEDU/adgsB9zqJfnA1lkPFZwwcvgbSqt6VLaOwExw6sPp5eaxprldcDiAHY+iw34zHbSs7QbhfYeMIgzPg+bkXpyyg/OESgn5HnxZT+EmcnA=
  template:
    metadata:
      name: patient-db-secret
      namespace: medconnect-dev
